M48
; DRILL file {KiCad 7.0.10-dirty} date Sun Feb  4 15:30:17 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-04T15:30:17-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-dirty
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X116.33Y-60.91
X116.8Y-113.01
X152.46Y-60.99
X152.89Y-113.0
M30
